# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - python-gRPC-Containe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://libraryacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_552300a5bab346a096f0c9b3c9b2ec0a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7ea733c36d5745ceb693e10ec4cc0ab5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: libraryacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_552300a5bab346a096f0c9b3c9b2ec0a }}/python-grpc:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'python-gRPC-Containe'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_26735853cdde47e2ba8a3189c4f90a60 }}
        images: 'libraryacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_552300a5bab346a096f0c9b3c9b2ec0a }}/python-grpc:${{ github.sha }}'